- name: Populate service facts
  ansible.builtin.service_facts:

- name: Get K3S install script
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services

- name: Install K3s
  block: 
    - name: Run k3s install script
      ansible.builtin.command: 
        cmd: /tmp/k3s-install.sh
        creates: /usr/local/bin/k3s
    - name: Restart ks3
      ansible.builtin.service: 
        name: k3s
        state: restarted
        enabled: true
    - name: Sleep a bit
      ansible.builtin.pause:
        seconds: 15
    - name: Get node information 
      ansible.builtin.command: 
        cmd: "kubectl get node"
      register: kubectl_node
  when: install_k3s| bool

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ user }}/.kube/"
    state: directory

- name: Create kube config 
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ user }}/.kube/config"
