- name: Populate service facts
  ansible.builtin.service_facts:

- name: Get K3S install script
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services

- name: Run k3s install script
  ansible.builtin.command: 
    cmd: /tmp/k3s-install.sh
    creates: /usr/local/bin/k3s

- name: Restart ks3
  ansible.builtin.service: 
    name: k3s
    state: restarted
    enabled: true
