---
- hosts: all
  vars_files:
    - vars.yml
  become: yes
  gather_facts: yes
  tasks:

    - name: Remove ~/.kube
      ansible.builtin.file: 
        path: "{{ansible_user}}/.kube"
        state: absent

    - name: Remove Acorn
      ansible.builtin.file: 
        path: "/usr/local/bin/acorn"
        state: absent

    - name: Run k3s uninstall script
      ansible.builtin.command: 
        cmd: k3s-uninstall.sh
      ignore_errors: yes



